### ISSUE TITLE
Provide fallback for crypto.randomUUID

### ISSUE THREAD

**Issue by tnajdek** [zotero/epub.js#1]
This [commit](https://github.com/zotero/epub.js/commit/e7b6b0cb8b3da04bdf2f12b4caa15eb424de5e90) switches to `crypto.randomUUID` with no fallback. This function is only available in [secure context](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) in [recent browsers](https://caniuse.com/?search=randomUUID), that means it will break demo if it is accessed via network ip and not localhost. It also severely limits which browsers can display an epub document. I agree with the optimization but it should include old method as a fallback or a polyfill for these scenarios.

**Comment by AbeJellinek** [comment]
Fixed in fc79087dc9eb6676c7f5a3e2069c4bfaf424d2ec
